version: '3.2'
services:
    i2b2-pg:
        image: i2b2/i2b2-pg:p1
        container_name: i2b2-pg
        ports:
            - "5432:5432"

    i2b2-wildfly:
        #image: i2b2/i2b2-wildfly:0.1
        #image: jboss/wildfly:10.0.0.Final
        container_name: i2b2-wildfly
        build: ./i2b2-wildfly/.

        environment:
            - DS_IP=i2b2-pg
            - DS_PASS=demouser
            - DS_PORT=5432
        
        #volumes:
        #    - ./standalone:/opt/jboss/wildfly/standalone
        ports:
            - "8080:8080"
            - "9900:9900"

    i2b2-web:
        container_name: i2b2-web
        image: i2b2/i2b2-web:p1
        command: /run-httpd.sh localhost
        ports:
            - "80:80"
            - "443:443"
